sandeepmistry/arduino-nRF5

boards.txt, platform.txt, variants/Waveshare_BLE400/pins_arduino.h, variants/Waveshare_BLE400/variant.cpp, variants/Waveshare_BLE400/variant.h
Sandeep, I added the 2 lines needed for the IDE to support the "Export compiled Binary" menu feature, (on the Sketch menu).
I've set this to use the hex version of file rather than the binary (bin) version, as the Hex file has the start offset in it, which will be needed if anyone wants to upload using JFlash etc
=> Add platform.txt recipe for 'Export compiled binary' as a hex file

package_nRF5_boards_index.json
Prevents error "Tool openocd is not available for your operating system." on 64 bit Linux systems.
=> support x86_64 Linux

.travis.yml, README.md, boards.txt, variants/PCA1000X/pins_arduino.h, variants/PCA1000X/variant.cpp, variants/PCA1000X/variant.h, variants/Taida_Century_nRF52_minidev/pins_arduino.h, variants/Taida_Century_nRF52_minidev/variant.cpp, variants/Taida_Century_nRF52_minidev/variant.h
nRF51: PCA1000X come from Nordic nRF51 DK
Generic nRF52: Same like "Generic nRF51"
nRF52_minidev: This board is available via aliexpress when searching for nrf52832
I have added hardware flow control to UART driver to support PCA10000.
=> Support for some NRF boards

cores/nRF5/Uart.cpp, cores/nRF5/Uart.h
Adds hardware flow control to UART/UARTE. To enable RTS/CTS define PIN_SERIAL_CTS and PIN_SERIAL_RTS
=> Add UART hardware flow control

cores/nRF5/wiring_analog_nRF52.c
Signed-off-by: Joerg Hubschneider <joerg.hubschneider@bosch-si.com>
a modified standard AnalogInput example with helping comment is attached:
[test_AnalogInput.zip](https://github.com/sandeepmistry/arduino-nRF5/files/631001/test_AnalogInput.zip)
=> analogRead() fix for nRF52 by setting related gain.

boards.txt
This sets the LF CLK source for all variants except the generic variants. I've only left the menu items for generic boards, if someone wants to tests an alternative LF CLK source for a non-generic board, they should just use the generic variant instead - as this keeps the boards.txt cleaner.
@dlabun please review, after this is merged, we can finally make a new v0.3.0 release.
=> LF CLCK source cleanup

libraries/Wire/Wire_nRF51.cpp, libraries/Wire/Wire_nRF52.cpp
As discussed in #93.
cc/ @maker-ja @dlabun
=> Use GPIO_PIN_CNF_DRIVE_S0D1 for Wire lib pin configurations

variants/nRF52DK/variant.cpp, variants/nRF52DK/variant.h
Hi @sandeepmistry!
1st off, congrats for this amazing repo, I've been following your work for a while and it's always a pleasure to read and use your code.
About this pull request, it's a simple modification that allows accessing to all the analog pins of the nRF52.
The Arduino environment doesn't allow it by default but several forks (such as Teensy) have more analog inputs and a similar approach.
Let me know if this PR is not formatted as it should, any feedback or suggestion would be more than welcome.
Thanks again for this great project,
Cedric ;)
PS: As an example, the modification is used it here:
https://github.com/honnet/nRF52AnalogTx/blob/master/nRF52AnalogTx.ino#L14
=> Allow access to the 8 analog inputs (VS 6 previously).

boards.txt
Tiny PR to correct the build.board name so we can identify the micro:bit board in the preprocessor.
=> Set microbit build.board value

boards.txt
Since the micro:bit comes with a DAPLink uC, we can configure CMSIS-DAP as the default uploader.
=> Set CMSIS-DAP as the default uploader for the micro:bit

variants/BBCmicrobit/variant.h, variants/BLENano/variant.h, variants/BluzDK/variant.h, variants/Generic/variant.h, variants/PCA1000X/variant.h, variants/RedBearLab_nRF51822/variant.h, variants/RedBear_BLENano2/variant.h, variants/RedBear_Blend2/variant.h, variants/Taida_Century_nRF52_minidev/variant.h, variants/Waveshare_BLE400/variant.h, variants/nRF52DK/variant.h, variants/ng-beacon/variant.h
So that arduino sketches can refer directly to `SDA` and `SCL` pins.
I've only added these variables to variants with `PIN_WIRE_SDA` and `PIN_WIRE_SCL` already defined, although one or two already had them.
=> Add SDA and SCL pin constants to variant definitions.

libraries/Wire/Wire.h, libraries/Wire/Wire_nRF51.cpp
As the nRF51 TWI implementation is master only and is not interrupt driven, there is no need to have any of the interrupt code present in this version.
Also, since the constructor signature is already different to the nRF52 version, is not like it could be kept for compatibility reasons.
=> Remove unused interrupt from nRF51 Wire lib

boards.txt, platform.txt, programmers.txt
I believe upload.interface is incorrect, and upload.protocol is the proper command
cmsisdap was mispelled
and cmsisdap will probably? always need swd option
See #111
=> consolidates to using .protocol instead of .interface and correct defines

README.md
The previous markdown renders as:
For 64-bit Linux users,  ```libc6:i386```, ```libstdc++6:i386```, ```libncurses5:i386```` and ```libudev1:i386``` need to be installed :
=> Fix minor markup error in README.md

cores/nRF5/wiring_analog.h, cores/nRF5/wiring_analog_nRF51.c
So, during my tests I noticed that my ADC readings were a bit off. Basically on a voltage of around 3.27v where I would expect the ADC value to be close to the maximum of 10-bit range I was instead reading values slightly above 900.
So for default ADC configuration, the first thing to note is the macro used to set `ADC_CONFIG_INPSEL` was assigning a `ADC_CONFIG_RES` value instead of one of the INPSEL ones. This value, happended to be the same as having 1/3 prescaler on the input signal (so in this case my 3.27v input would be scaled to 1/3 of its value before reaching the ADC comparator). The `ADC_CONFIG_REFSEL` value was then set to the internal voltage reference, which is 1.2V, so in essence, together with the prescaler the ADC was configured to read voltages from 0 to 3.6V. I guess …
=> Fix ADC prescaler reg config, add prescaler options

libraries/Wire/Wire.h, libraries/Wire/Wire_nRF51.cpp
I've been having issues reading I2C data using the TWI driver. In the smallest test case
I was reading 2 individual bytes one after another in a loop and the data returned from the 'Wire.read()' was in the incorrect order.
The operation itself is very simple, send a write command selecting the register to be read and then read a single byte back. The operation should read register `0` with value `0x40` and then register `1` with value `0x00`, as shown in the image below. The bus looks exactly the same with and without this patch, but without it the software was returning the value of register `0` as `0x00` and register `1` as `0x40`.
The fix is achieved by enabling during read the shortcut between the "byte boundary event" and the "suspend task" for each read byte (so when it receives a …
=> Fix nRF51 I2C read operation

cores/nRF5/wiring_analog_nRF51.c
So that the ADC input range is configured from 0 to Vdd instead of the current 0 to 3.6V, as discussed in #142.
=> Set nRF51 default ADC to 1/3 prescaler and 1/3 reference voltage

libraries/Wire/Wire.h, libraries/Wire/Wire_nRF51.cpp
The changes in #137 don't work with trying to use `stopBit = false`. Minor change to allow doing a `requestFrom` in multiple parts. This is necessary due to limited buffer sizes.
Example usage of what this allows (which doesn't currently work):
```
uint8_t buffer[20];
Wire.requestFrom(address, 10, false);
for (uint8_t i=0; i < 10; i++) {
buffer[i] = Wire.read();
}
// Do something else, then finish reading
Wire.requestFrom(address, 10);
for (uint8_t i=0; i < 10; i++) {
buffer[10 + i] = Wire.read();
}
```
@carlosperate, any thoughts on this PR? It's tested and works, but it's kind of quick and dirty as I needed it working ASAP.
=> Fix stopBit = false mode in nRF51 Wire library

cores/nRF5/wiring_analog_nRF52.c
I'm not 100% sure this PR is correct, I've only got anecdotal evidence, haven't been able to find anything concrete that says this is correct, but I believe it to be.
Tried using `analogWrite` to power an LED and found that it seemed inverted - a value of 255 turned the LED off and 0 turned it full on. As per [Arduino documentation](https://www.arduino.cc/en/Reference/AnalogWrite) 255 should be "always on".
The 15th bit in the PWM value [controls polarity](http://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.nrf52832.ps.v1.1%2Fpwm.html) on the nRF52. Setting this to 1 made the LED act as expected. In the Adafruit core, they have an `inverted` argument which defaults to `false` and [sets the polarity to falling …
=> Use falling edge polarity for PWM to match standard Arduino

README.md, platform.txt, programmers.txt
In support of 'issue' #183 - Add Black Magic Probe (BMP) upload method  …
This is basically a merge of work done by @rogerclarkmelbourne in arduino-nRF5-customised, with the addition of bootloader uploading as per @sandeepmistry openocd reference in platform.txt
Note: This incorporates changes based off feedback from @sandeepmistry, @dmikhalsky, @dlabun
* README.md - BMP driver installation details
* platform.txt - BMP tool setup
* programmers.txt - Add BMP as a programmer option
=> Black magic probe issue #183

cores/nRF5/Uart.cpp, cores/nRF5/Uart.h, libraries/SPI/SPI.cpp, libraries/SPI/SPI.h, libraries/Wire/Wire.h, libraries/Wire/Wire_nRF51.cpp, libraries/Wire/Wire_nRF52.cpp
Hi again @sandeepmistry & @dlabun!
As said in the issue #213, this Generic variant that you offer here is a really great feature, but the default Wire/Serial/SPI objects are initialized with default pins that are forced.
It makes sense for most boards, but maybe not for the generic variants as these forced pins could be unavailable.
The 3 commits of this pull requests implement a setPins(...) method for the 3 objects aforementioned (Wire/Serial/SPI), calling it before its respective begin() would solve the problem.
Let me know if there's anything I can do to improve these commits...
Cedric ;)
=> Custom I2C/SPI/UART pins for generic variants

.travis.yml, README.md, boards.txt, variants/PCA1000X/variant.h
This PR adds a PCA1000X board variant called PCA10001, for the PCA10001 development board.
=> Add PCA1000X variant PCA10001

boards.txt
The _build.extra_flags_ for PCA1000X boards include `-D{board.variant}`:
`PCA1000X.build.extra_flags=-DNRF51 -D{board.variant}`
However, this extra flag is currently not also part of the _build.extra_flags_ of the PCA1000X softdevices:
```
PCA1000X.menu.softdevice.s110.build.extra_flags=-DNRF51 -DS110 -DNRF51_S110
[...]
PCA1000X.menu.softdevice.s130.build.extra_flags=-DNRF51 -DS130 -DNRF51_S130
```
Because of this, `-D{board.variant}` will actually only be used on PCA1000X boards when selecting softdevice "none".
On PCA1000X boards that require hardware flow control for UART communication (like the PCA10000 and PCA10001), this for example leads to the strange effect that serial port communication currently only works when selecting softdevice "none".
=> Add -D{board.variant} to build.extra_flags of PCA1000X softdevices

libraries/Wire/Wire_nRF52.cpp
This is fixing the lock-ups that are described in #108, #207, and #199. The problem (at least in the case of the I2C scanner that I had to deal with) is related to an empty tx buffer, so the LASTTX event never occurres, resulting into an endless loop.
=> Fix I2C lock-up when endTransmission() is called with empty txBuffer

platform.txt
This fixes the `\\.\/dev/ttyACM0: No such file or directory` error on Linux.
=> Remove '\\.\', closes #245

.travis.yml, README.md, boards.txt, variants/DWM1001-DEV/pins_arduino.h, variants/DWM1001-DEV/variant.cpp, variants/DWM1001-DEV/variant.h
Hi,
I have added support for decaWave DWM1001-DEV board. I am not working for decaWave so this is an **unofficial** port. I have tried to optimize the pinout based on the available pins. [Here](https://github.com/sandeepmistry/arduino-nRF5/files/2495097/dwm1001-dev_arduino_pinout.pdf) is a document explaining the pinout.
It would be great if you could merge it.
Thanks
=> Added decaWave DWM1001-DEV board

cores/nRF5/HardwareSerial.h
Not all functions of HardwareSerial are declared as pure virtual. This leads to "undefined reference to `vtable for HardwareSerial'" errors when used via Segger Studio.
=> fix for "undefined reference to `vtable for HardwareSerial'"

libraries/SPI/SPI.h
After commit https://github.com/sandeepmistry/arduino-nRF5/commit/0524008cca0432dba9da0dac5e665bb50ae7cd25#diff-ddd77aecb16ad4a70bea9989e9fd8022 the preprocessor if's are unbalanced. That endif as suggested in this pull request therefore should be added again.
=> Fix for broken SPI.h

cores/nRF5/avr/pgmspace.h
Bugfix PR for pgm_read_ptr macro. See also:
- https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/502 (spotted and fixed by me)
- https://github.com/arduino/ArduinoCore-samd/blob/master/cores/arduino/avr/pgmspace.h#L106 (identical fix in a different repo by somebody else)
=> Fixing pgm_read_ptr macro bug

variants/CalliopeMini/variant.cpp, variants/CalliopeMini/variant.h
Make connector pins 16 and 17 available as analog inputs A6 and A7
Update pin map comments in variant.cpp
Swap microphone (P0.03) with unused pin (P0.23) in the pin map to make it easier to prevent digital pin access to the microphone pin.
(The microphone pin should never be used as a digital output since that could damage the microphone amplifier).
P0.03 is now g_ADigitalPinMap[28]. Since PIN_A0 now points to that entry, and the microphone is only accessed by reading analog pin A0.
This change should be transparent to any existing code.
=> Calliope: Add analog pins A6-A7

cores/nRF5/pulse.c
Map the pin number argument to internal pin number using digitalPinToPin() macro
Adjust the loop count to microsecond computations (based on empirical timing measurements of actual pulses with an oscilloscope). Tested on both nRF51 and nRF52 boards.
=> Two tweaks to pulseIn()

softdevices.txt
Hi all!
As you can see in the commit, the new URLs look more "durable", so this commit should fix the download problem for a while.
Note: to avoid changing any behavior, this commit only allows downloading the exact same versions of the SD, but there are much more recent ones:
https://www.nordicsemi.com/Software-and-tools/Software/S132/Download#infotabs
https://www.nordicsemi.com/Software-and-tools/Software/S130/Download#infotabs
=> If any of you is confident about the retro-compatibility of the new SD, I'd be happy to improve this pull request.
Thanks again for this great project!
Cedric ;)
=> Fix #312: softdevice download links should be stable now.

cores/nRF5/WInterrupts.c
Priority 1 is reserved by the SoftDevice and shall not be used by any application code.
BLE stack doesn't work correctly together with attachInterrupt as reported [here](https://github.com/sandeepmistry/arduino-BLEPeripheral/issues/205).
Priority 2 is the correct one for high priority interrupts [according to the docs](https://infocenter.nordicsemi.com/topic/sds_s132/SDS/s1xx/processor_avail_interrupt_latency/exception_mgmt_sd.html).
=> Fixed GPIOTE interrupt priority

cores/nRF5/Arduino.h
These functions were using the `OUTSET` and `DIRSET` registers instead of `OUT` and `DIR`. The `SET` version of these registers only do something when a "1" is written to any of their bits, writting a "0" does nothing.
From the nRF52833 datasheet:
Found this issue when using some of the Adafruit libraries using a `BUSIO_USE_FAST_PINIO` macro that enables utilisation of these functions, and noticed that some of the pins were not being driven low, only high.
Using this patch locally fixed the issue.
=> Fix Arduino.h `portOutputRegister()` and `portModeRegister()`

.github/workflows/compile.yml, README.md, boards.txt, variants/CalliopeminiV3/pins_arduino.h, variants/CalliopeminiV3/variant.cpp, variants/CalliopeminiV3/variant.h
Dear Sandeep Mistry, 
thank you a lot for your great work! 
this Pull Request adds the Calliope mini as a NRF52833 device to the NRF5 Arduino library. The Calliope mini 3 is partly based on the micro:bit v2 for best compatibility with IDEs and software frameworks. So big parts of the pinout is completely equivalent to the micro:bit v2 as well as the DAPLink PID and VID, but additional pins have been added for the support of: 
- 3 internal RGB leds,
- touch pad 3, the 
- analog input of the grove connector  
- motor driver. 
On this [link](https://calliope.cc/calliope-mini-3) you can find additional info.
I touched the following files: 
- README.md
- boards.txt
- variants/CalliopeminiV3/pins_arduino.h
- variants/CalliopeminiV3/variant.cpp
- variants/CalliopeminiV3/variant.h
The .json file …
=> adds Calliope mini V3 to the library

variants/CalliopeminiV3/variant.cpp, variants/CalliopeminiV3/variant.h
Dear Sandeep, 
we found out, that the analog pin A3 was wrongly connected to pin 3, and corrected that. Also the pin 16 was not available within the analog pin notation, so we added this as well. in _variant.cpp_ only one comment was corrected. I think this change is minor and does not necessarily need a new releaase, since all the pins were already accessible using pin numbers. Still good, to have it in the future. 
Kind regards,
Hugo
=> corrects A3 from pin 3 to pin 18(C18), adds A7 as pin 16(C16)
